<?php

/*
 | Posisi textbox nomor surat per jenis dokumen.
 | Koordinat memakai rasio halaman A4: 0.0 sampai 1.0.
 | File ini dikalibrasi dari 51 view PDF yang dikirim pengguna.
 */

return [
    'documents' => [
        // Pernyataan Mengizinkan Ikut Kk
        'suratpernyataanmengizinkanikutkk' => [
            'model' => \App\Models\surat_pernyataan_mengizinkan_ikut_kk::class,
            'view' => 'surat.pdf_pernyataan_mengizinkan_ikut_kk',
            'aliases' => [
                'suratpernyataanmengizinkanikutkk',
                'pernyataan_mengizinkan_ikut_kk_suami_istri_keluarga',
                'pdf_pernyataan_mengizinkan_ikut_kk',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14888,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02271,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 10.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'pernyataan_mengizinkan_ikut_kk',
        ],

        // Surat Keterangan Desa Sebagai Penduduk
        'suratketerangandesasebagaipenduduk' => [
            'model' => \App\Models\SuratKeteranganDesaSebagaiPenduduk::class,
            'view' => 'surat.pdf_surat_keterangan_desa_sebagai_penduduk',
            'aliases' => [
                'suratketerangandesasebagaipenduduk',
                'surat_keterangan_desa_sebagai_penduduk',
                'desa_penduduk',
                'desa-sebagai-penduduk',
                'pdf_surat_keterangan_desa_sebagai_penduduk',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.15870,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02647,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.80,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_desa_sebagai_penduduk',
        ],

        // Surat Kuasa
        'suratkuasa' => [
            'model' => \App\Models\SuratKuasa::class,
            'view' => 'surat.pdf_surat_kuasa',
            'aliases' => [
                'suratkuasa',
                'surat_kuasa',
                'kuasa',
                'pdf_surat_kuasa',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'No :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.13278,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02200,
                'fontFamily' => 'Arial',
                'fontSizePt' => 10.80,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_kuasa',
        ],

        // Surat Pernyataan Miskin
        'suratpernyataanmiskin' => [
            'model' => \App\Models\SuratPernyataanMiskin::class,
            'view' => 'surat.pdf_surat_pernyataan_miskin',
            'aliases' => [
                'surat_pernyataan_miskin',
                'pernyataan_miskin',
                'suratpernyataanmiskin',
                'pdf_surat_pernyataan_miskin',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.15547,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02380,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_pernyataan_miskin',
        ],

        // Rekomendasi Bbm
        'rekomendasibbm' => [
            'model' => \App\Models\SuratRekomendasiBbm::class,
            'view' => 'surat.pdf_rekomendasi_bbm',
            'aliases' => [
                'rekomendasi_bbm',
                'surat_rekomendasi_bbm',
                'surat-rekomendasi-bbm',
                'suratrekomendasibbm',
                'pdf_rekomendasi_bbm',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.12763,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02203,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'rekomendasi_bbm',
        ],

        // Permohonan Pernyataan Miskin
        'permohonanpernyataanmiskin' => [
            'model' => \App\Models\SuratPermohonanPernyataanMiskin::class,
            'view' => 'surat.pdf_permohonan_pernyataan_miskin',
            'aliases' => [
                'permohonan_pernyataan_miskin',
                'permohonanpernyataanmiskin',
                'surat_permohonan_pernyataan_miskin',
                'suratpermohonanpernyataanmiskin',
                'pdf_permohonan_pernyataan_miskin',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05500,
                'yRatio' => 0.10457,
                'widthRatio' => 0.58000,
                'heightRatio' => 0.02200,
                'fontFamily' => 'Arial',
                'fontSizePt' => 9.80,
                'alignment' => 'left',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'permohonan_pernyataan_miskin',
        ],

        // Permohonan Tebang Pohon
        'permohonantebangpohon' => [
            'model' => \App\Models\SuratPermohonanTebangPohon::class,
            'view' => 'surat.pdf_permohonan_tebang_pohon',
            'aliases' => [
                'permohonan_tebang_pohon',
                'tebangpohon',
                'surat_permohonan_tebang_pohon',
                'pdf_permohonan_tebang_pohon',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05500,
                'yRatio' => 0.10725,
                'widthRatio' => 0.72000,
                'heightRatio' => 0.02200,
                'fontFamily' => 'Arial',
                'fontSizePt' => 10.30,
                'alignment' => 'left',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'permohonan_tebang_pohon',
        ],

        // Surat Nota Angkutan
        'notaangkutan' => [
            'model' => \App\Models\SuratNotaAngkutan::class,
            'view' => 'surat.pdf_surat_nota_angkutan',
            'aliases' => [
                'nota_angkutan',
                'notaangkutan',
                'surat_nota_angkutan',
                'pdf_surat_nota_angkutan',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.23443,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02200,
                'fontFamily' => 'Arial',
                'fontSizePt' => 10.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_nota_angkutan',
        ],

        // Surat Ijin Keluarga
        'suratijinkeluarga' => [
            'model' => \App\Models\SuratIjinKeluarga::class,
            'view' => 'surat.pdf_surat_ijin_keluarga',
            'aliases' => [
                'surat_ijin_keluarga',
                'ijin_keluarga',
                'suratijin_keluarga',
                'suratijinkeluarga',
                'pdf_surat_ijin_keluarga',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.11985,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02200,
                'fontFamily' => 'Arial',
                'fontSizePt' => 10.30,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_ijin_keluarga',
        ],

        // Surat Perintah Perjalanan Dinas
        'perintahperjalanandinas' => [
            'model' => \App\Models\SuratPerintahPerjalananDinas::class,
            'view' => 'surat.pdf_surat_perintah_perjalanan_dinas',
            'aliases' => [
                'perintah_perjalanan_dinas',
                'perjalanan_dinas',
                'sppd',
                'surat_perintah_perjalanan_dinas',
                'perintahperjalanandinas',
                'suratperintahperjalanandinas',
                'pdf_surat_perintah_perjalanan_dinas',
            ],
            'number_fields' => [
                'nomor_sppd',
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'SPPD No. :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.51000,
                'yRatio' => 0.64729,
                'widthRatio' => 0.44000,
                'heightRatio' => 0.02200,
                'fontFamily' => 'Arial',
                'fontSizePt' => 9.50,
                'alignment' => 'left',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_perintah_perjalanan_dinas',
        ],

        // Surat Undangan
        'undangan' => [
            'model' => \App\Models\SuratUndangan::class,
            'view' => 'surat.pdf_surat_undangan',
            'aliases' => [
                'undangan',
                'surat_undangan',
                'suratundangan',
                'pdf_surat_undangan',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05500,
                'yRatio' => 0.13168,
                'widthRatio' => 0.55000,
                'heightRatio' => 0.02509,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 12.00,
                'alignment' => 'left',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_undangan',
        ],

        // Surat Keterangan Kepemilikan Aset
        'suratketerangankepemilikanaset' => [
            'model' => \App\Models\SuratKeteranganKepemilikanAset::class,
            'view' => 'surat.pdf_surat_keterangan_kepemilikan_aset',
            'aliases' => [
                'surat_keterangan_kepemilikan_aset',
                'kepemilikan_aset',
                'suratketerangankepemilikanaset',
                'pdf_surat_keterangan_kepemilikan_aset',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.11239,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02200,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 10.00,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_kepemilikan_aset',
        ],

        // Surat Pernyataan Kepemilikan Dokumen Asli
        'suratpernyataankepemilikandokumenasli' => [
            'model' => \App\Models\SuratPernyataanKepemilikanDokumenAsli::class,
            'view' => 'surat.pdf_surat_pernyataan_kepemilikan_dokumen_asli',
            'aliases' => [
                'surat_pernyataan_kepemilikan_dokumen_asli',
                'pernyataan_kepemilikan_dokumen',
                'suratpernyataankepemilikandokumenasli',
                'pdf_surat_pernyataan_kepemilikan_dokumen_asli',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.16086,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02468,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_pernyataan_kepemilikan_dokumen_asli',
        ],

        // Surat Keterangan Penghasilan
        'suratketeranganpenghasilan' => [
            'model' => \App\Models\surat_keterangan_penghasilan::class,
            'view' => 'surat.pdf_surat_keterangan_penghasilan',
            'aliases' => [
                'surat_keterangan_penghasilan',
                'suratketeranganpenghasilan',
                'penghasilan',
                'pdf_surat_keterangan_penghasilan',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14896,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02556,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_penghasilan',
        ],

        // Surat Keterangan Domisili Warga
        'suratketerangandomisiliwarga' => [
            'model' => \App\Models\SuratKeteranganDomisiliWarga::class,
            'view' => 'surat.pdf_surat_keterangan_domisili_warga',
            'aliases' => [
                'surat_keterangan_domisili_warga',
                'domisili_warga',
                'suratketerangandomisiliwarga',
                'pdf_surat_keterangan_domisili_warga',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'No :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14602,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02487,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.50,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_domisili_warga',
        ],

        // Surat Perintah Tugas
        'suratperintahtugas' => [
            'model' => \App\Models\SuratPerintahTugas::class,
            'view' => 'surat.pdf_surat_perintah_tugas',
            'aliases' => [
                'surat_perintah_tugas',
                'perintah_tugas',
                'suratperintahtugas',
                'pdf_surat_perintah_tugas',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.13121,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02200,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_perintah_tugas',
        ],

        // Surat Keterangan Ghoib
        'suratketeranganghoib' => [
            'model' => \App\Models\surat_keterangan_ghoib::class,
            'view' => 'surat.pdf_surat_keterangan_ghoib',
            'aliases' => [
                'surat_keterangan_ghoib',
                'ghoib',
                'pdf_surat_keterangan_ghoib',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14746,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02468,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_ghoib',
        ],

        // Surat Keterangan Desa Miskin
        'suratketerangandesamiskin' => [
            'model' => \App\Models\SuratKeteranganDesaMiskin::class,
            'view' => 'surat.pdf_surat_keterangan_desa_miskin',
            'aliases' => [
                'suratketerangandesamiskin',
                'surat_keterangan_desa_miskin',
                'miskindesa',
                'pdf_surat_keterangan_desa_miskin',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14602,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02487,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.50,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_desa_miskin',
        ],

        // Ahli Waris Desa
        'suratketeranganahliwarisdesa' => [
            'model' => \App\Models\surat_keterangan_ahli_waris_desa::class,
            'view' => 'surat.pdf_ahli_waris_desa',
            'aliases' => [
                'surat_keterangan_ahli_waris_desa',
                'ahliwarisdesa',
                'suratketeranganahliwarisdesa',
                'pdf_ahli_waris_desa',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.13264,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02836,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.80,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'ahli_waris_desa',
        ],

        // Surat Keterangan Miskin Skm
        'suratketeranganmiskinskm' => [
            'model' => \App\Models\SuratKeteranganMiskinSkm::class,
            'view' => 'surat.pdf_surat_keterangan_miskin_skm',
            'aliases' => [
                'suratketeranganmiskinskm',
                'surat_keterangan_miskin_skm',
                'skm',
                'pdf_surat_keterangan_miskin_skm',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14602,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02487,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.50,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_miskin_skm',
        ],

        // Surat Keterangan Numpang Nikah
        'suratketerangannumpangnikah' => [
            'model' => \App\Models\surat_keterangan_numpang_nikah::class,
            'view' => 'surat.pdf_surat_keterangan_numpang_nikah',
            'aliases' => [
                'suratketerangannumpangnikah',
                'surat_keterangan_numpang_nikah',
                'numpang_nikah',
                'pdf_surat_keterangan_numpang_nikah',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Reg. No :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14366,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02200,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 10.80,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_numpang_nikah',
        ],

        // Surat Keterangan Kematian Desa
        'suratketerangankematiandesa' => [
            'model' => \App\Models\surat_keterangan_kematian_desa::class,
            'view' => 'surat.pdf_surat_keterangan_kematian_desa',
            'aliases' => [
                'suratketerangankematiandesa',
                'surat_keterangan_kematian_desa',
                'kematian_desa',
                'pdf_surat_keterangan_kematian_desa',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.15508,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02647,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.80,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_kematian_desa',
        ],

        // Surat Sptjm Suami Istri
        'suratsptjmsuamiistri' => [
            'model' => \App\Models\surat_sptjm_suami_istri::class,
            'view' => 'surat.pdf_surat_sptjm_suami_istri',
            'aliases' => [
                'surat_sptjm_suami_istri',
                'sptjm_suami_istri',
                'pdf_surat_sptjm_suami_istri',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.13143,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02292,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_sptjm_suami_istri',
        ],

        // Pernyataan Pembetulan Data Tidak Merubah Lagi
        'suratpernyataanpembetulandatatidakmerubahlagi' => [
            'model' => \App\Models\surat_pernyataan_pembetulan_data_tidak_merubah_lagi::class,
            'view' => 'surat.pdf_pernyataan_pembetulan_data_tidak_merubah_lagi',
            'aliases' => [
                'suratpernyataanpembetulandatatidakmerubahlagi',
                'pernyataan_pembetulan_data_tidak_merubah_lagi',
                'pdf_pernyataan_pembetulan_data_tidak_merubah_lagi',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14888,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02271,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 10.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'pernyataan_pembetulan_data_tidak_merubah_lagi',
        ],

        // Surat Permohonan Pengantar Keabsahan Akta Kelahiran
        'suratpermohonanpengantarkeabsahanaktakelahiran' => [
            'model' => \App\Models\surat_permohonan_pengantar_keabsahan_akta_kelahiran::class,
            'view' => 'surat.pdf_surat_permohonan_pengantar_keabsahan_akta_kelahiran',
            'aliases' => [
                'surat_permohonan_pengantar_keabsahan_akta_kelahiran',
                'permohonan_pengantar_keabsahan_akta_kelahiran',
                'pdf_surat_permohonan_pengantar_keabsahan_akta_kelahiran',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.12247,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02355,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 10.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_permohonan_pengantar_keabsahan_akta_kelahiran',
        ],

        // Surat Pernyataan Batal Pindah Penduduk
        'suratpernyataanbatalpindahpenduduk' => [
            'model' => \App\Models\surat_pernyataan_batal_pindah_penduduk::class,
            'view' => 'surat.pdf_surat_pernyataan_batal_pindah_penduduk',
            'aliases' => [
                'surat_pernyataan_batal_pindah_penduduk',
                'pernyataan_batal_pindah_penduduk',
                'pdf_surat_pernyataan_batal_pindah_penduduk',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.15333,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02380,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_pernyataan_batal_pindah_penduduk',
        ],

        // Surat Formulir Pengajuan User Id
        'suratformulirpengajuanuserid' => [
            'model' => \App\Models\surat_formulir_pengajuan_user_id::class,
            'view' => 'surat.pdf_surat_formulir_pengajuan_user_id',
            'aliases' => [
                'surat_formulir_pengajuan_user_id',
                'formulir_pengajuan_user_id',
                'pdf_surat_formulir_pengajuan_user_id',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.10656,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02292,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_formulir_pengajuan_user_id',
        ],

        // Pernyataan Perubahan Data Pendidikan
        'suratpernyataanperubahandatapendidikan' => [
            'model' => \App\Models\surat_pernyataan_perubahan_data_pendidikan::class,
            'view' => 'surat.pdf_pernyataan_perubahan_data_pendidikan',
            'aliases' => [
                'suratpernyataanperubahandatapendidikan',
                'pdf_pernyataan_perubahan_data_pendidikan',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14888,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02271,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 10.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'pernyataan_perubahan_data_pendidikan',
        ],

        // Suratketerangankehilangan
        'suratketerangankehilangan' => [
            'model' => \App\Models\surat_keterangan_kehilangan::class,
            'view' => 'surat.pdfsuratketerangankehilangan',
            'aliases' => [
                'suratketerangankehilangan',
                'pdfsuratketerangankehilangan',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.15493,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02487,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'suratketerangankehilangan',
        ],

        // Suratpernyataantidakbisamelampirkanktpkematian
        'suratpernyataantidakbisamelampirkanktpkematian' => [
            'model' => \App\Models\surat_pernyataan_tidak_bisa_melampirkan_ktp_kematian::class,
            'view' => 'surat.pdfsuratpernyataantidakbisamelampirkanktpkematian',
            'aliases' => [
                'suratpernyataantidakbisamelampirkanktpkematian',
                'pdfsuratpernyataantidakbisamelampirkanktpkematian',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.16205,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02487,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'suratpernyataantidakbisamelampirkanktpkematian',
        ],

        // Surat Permohonan Pengantar Keabsahan Akta Kelahiran Anak
        'suratpermohonanpengantarkeabsahanaktakelahirananak' => [
            'model' => \App\Models\surat_permohonan_pengantar_keabsahan_akta_kelahiran_anak::class,
            'view' => 'surat.pdf_surat_permohonan_pengantar_keabsahan_akta_kelahiran_anak',
            'aliases' => [
                'surat_permohonan_pengantar_keabsahan_akta_kelahiran_anak',
                'permohonan_pengantar_keabsahan_akta_kelahiran_anak',
                'pdf_surat_permohonan_pengantar_keabsahan_akta_kelahiran_anak',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.12247,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02355,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 10.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_permohonan_pengantar_keabsahan_akta_kelahiran_anak',
        ],

        // Suratnumpangkk
        'suratpernyataannumpangkk' => [
            'model' => \App\Models\surat_pernyataan_numpang_kk::class,
            'view' => 'surat.pdfsuratnumpangkk',
            'aliases' => [
                'suratpernyataannumpangkk',
                'pdfsuratnumpangkk',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.20372,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02787,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 12.00,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'suratnumpangkk',
        ],

        // Surat Keterangan Tidakmampu
        'suratketerangantidakmampu' => [
            'model' => \App\Models\suratketerangantidakmampu::class,
            'view' => 'surat.pdf_surat_keterangan_tidakmampu',
            'aliases' => [
                'surat_keterangan_tidakmampu',
                'pdf_surat_keterangan_tidakmampu',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.15493,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02487,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_tidakmampu',
        ],

        // Surat Pernyataan Memilih Nama Alias
        'suratpernyataanmemilihnamaalias' => [
            'model' => \App\Models\surat_pernyataan_memilih_nama_alias::class,
            'view' => 'surat.pdf_surat_pernyataan_memilih_nama_alias',
            'aliases' => [
                'surat_pernyataan_memilih_nama_alias',
                'pdf_surat_pernyataan_memilih_nama_alias',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14780,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02487,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_pernyataan_memilih_nama_alias',
        ],

        // Surat Pernyataan Memilih Nama Alias Satu Ortu
        'suratpernyataanmemilihnamaaliassatuorangtua' => [
            'model' => \App\Models\nama_alias_ortu::class,
            'view' => 'surat.pdf_surat_pernyataan_memilih_nama_alias_satu_ortu',
            'aliases' => [
                'surat_pernyataan_memilih_nama_alias_satu_orang_tua',
                'surat_pernyataan_memilih_nama_alias_satu_ortu',
                'pdf_surat_pernyataan_memilih_nama_alias_satu_ortu',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14780,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02487,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_pernyataan_memilih_nama_alias_satu_ortu',
        ],

        // Surat Keterangan Desa Pernah Menikah
        'suratketerangandesapernahmenikah' => [
            'model' => \App\Models\surat_keterangan_desa_pernah_menikah::class,
            'view' => 'surat.pdf_surat_keterangan_desa_pernah_menikah',
            'aliases' => [
                'suratketerangandesapernahmenikah',
                'pdf_surat_keterangan_desa_pernah_menikah',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.15493,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02487,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_desa_pernah_menikah',
        ],

        // Surat Pernyataan Dan Jaminan
        'suratpernyataandanjaminan' => [
            'model' => \App\Models\surat_pernyataan_dan_jaminan::class,
            'view' => 'surat.pdf_surat_pernyataan_dan_jaminan',
            'aliases' => [
                'suratpernyataandanjaminan',
                'pdf_surat_pernyataan_dan_jaminan',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14480,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02200,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 10.50,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_pernyataan_dan_jaminan',
        ],

        // Surat Keterangan Ahli Waris
        'suratketeranganahliwaris' => [
            'model' => \App\Models\surat_keterangan_ahli_waris::class,
            'view' => 'surat.pdf_surat_keterangan_ahli_waris',
            'aliases' => [
                'suratketeranganahliwaris',
                'pdf_surat_keterangan_ahli_waris',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'No :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.12180,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02200,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 10.50,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_ahli_waris',
        ],

        // Surat Rekomendasi
        'rekomendasi' => [
            'model' => \App\Models\SuratRekomendasi::class,
            'view' => 'surat.pdf_surat_rekomendasi',
            'aliases' => [
                'rekomendasi',
                'surat_rekomendasi',
                'suratrekomendasi',
                'pdf_surat_rekomendasi',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05500,
                'yRatio' => 0.14337,
                'widthRatio' => 0.58000,
                'heightRatio' => 0.03293,
                'fontFamily' => 'Arial',
                'fontSizePt' => 12.00,
                'alignment' => 'left',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_rekomendasi',
        ],

        // Surat Pernyataan Kesanggupan
        'suratpernyataankesanggupan' => [
            'model' => \App\Models\SuratPernyataanKesanggupan::class,
            'view' => 'surat.pdf_surat_pernyataan_kesanggupan',
            'aliases' => [
                'surat_pernyataan_kesanggupan',
                'pernyataan_kesanggupan',
                'suratpernyataankesanggupan',
                'kesanggupan',
                'pdf_surat_pernyataan_kesanggupan',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.16086,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02468,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_pernyataan_kesanggupan',
        ],

        // Surat Pernyataan Tidak Punya Kartu Jkn
        'suratpernyataantidakpunyakartujkn' => [
            'model' => \App\Models\SuratPernyataanTidakPunyaKartuJkn::class,
            'view' => 'surat.pdf_surat_pernyataan_tidak_punya_kartu_jkn',
            'aliases' => [
                'surat_pernyataan_tidak_punya_kartu_jkn',
                'pernyataan_tidak_punya_kartu_jkn',
                'tidak_punya_kartu',
                'jamkesmas',
                'jkn',
                'suratpernyataantidakpunyakartujkn',
                'suratpernyataantidakpunyakartu',
                'pdf_surat_pernyataan_tidak_punya_kartu_jkn',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.15547,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02380,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_pernyataan_tidak_punya_kartu_jkn',
        ],

        // Surat Permohonan Pembukaan Rekening
        'permohonanpembukaanrekening' => [
            'model' => \App\Models\SuratPermohonanPembukaanRekening::class,
            'view' => 'surat.pdf_surat_permohonan_pembukaan_rekening',
            'aliases' => [
                'permohonan_pembukaan_rekening',
                'bukaanrekening',
                'surat_permohonan_pembukaan_rekening',
                'permohonanpembukaanrekening',
                'SuratPermohonanPembukaanRekening',
                'pdf_surat_permohonan_pembukaan_rekening',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05500,
                'yRatio' => 0.11792,
                'widthRatio' => 0.68000,
                'heightRatio' => 0.02200,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'left',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_permohonan_pembukaan_rekening',
        ],

        // Surat Pernyataan Belum Akta
        'suratpernyataanbelumakta' => [
            'model' => \App\Models\surat_pernyataan_belum_akta::class,
            'view' => 'surat.pdf_surat_pernyataan_belum_akta',
            'aliases' => [
                'suratpernyataanbelumakta',
                'pdf_surat_pernyataan_belum_akta',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14732,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02316,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.30,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_pernyataan_belum_akta',
        ],

        // Pernyataan Beda Nama Buku Nikah
        'suratpernyataanbedanamabukunikah' => [
            'model' => \App\Models\surat_pernyataan_beda_nama_buku_nikah::class,
            'view' => 'surat.pdf_pernyataan_beda_nama_buku_nikah',
            'aliases' => [
                'suratpernyataanbedanamabukunikah',
                'pdf_pernyataan_beda_nama_buku_nikah',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14732,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02316,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.30,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'pernyataan_beda_nama_buku_nikah',
        ],

        // Pernyataan Anak Seorang Nama Ibu
        'suratpernyataananakseorangnamaibu' => [
            'model' => \App\Models\surat_pernyataan_anak_seorang_nama_ibu::class,
            'view' => 'surat.pdf_pernyataan_anak_seorang_nama_ibu',
            'aliases' => [
                'surat_pernyataan_anak_seorang_nama_ibu',
                'pdf_pernyataan_anak_seorang_nama_ibu',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14732,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02316,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.30,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'pernyataan_anak_seorang_nama_ibu',
        ],

        // Pernyataan Akta Barcode Nomor Sama
        'suratpernyataanaktabarcodenomorsama' => [
            'model' => \App\Models\surat_pernyataan_akta_barcode_nomor_sama::class,
            'view' => 'surat.pdf_pernyataan_akta_barcode_nomor_sama',
            'aliases' => [
                'suratpernyataanaktabarcodenomorsama',
                'pdf_pernyataan_akta_barcode_nomor_sama',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.15405,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02885,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 12.00,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'pernyataan_akta_barcode_nomor_sama',
        ],

        // Sptjm Kematian
        'sptjmkematian' => [
            'model' => \App\Models\surat_sptjm_kematian::class,
            'view' => 'surat.pdf_sptjm_kematian',
            'aliases' => [
                'sptjmkematian',
                'pdf_sptjm_kematian',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.15280,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02203,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.00,
                'alignment' => 'center',
                'bold' => true,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'sptjm_kematian',
        ],

        // Surat Keterangan Harga Kepemilikan Tanah
        'suratketeranganhargakepemilikantanah' => [
            'model' => \App\Models\surat_keterangan_harga_kepemilikan_tanah::class,
            'view' => 'surat.pdf_surat_keterangan_harga_kepemilikan_tanah',
            'aliases' => [
                'suratketeranganhargakepemilikantanah',
                'pdf_surat_keterangan_harga_kepemilikan_tanah',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14732,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02487,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.50,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_harga_kepemilikan_tanah',
        ],

        // Skck
        'suratpengantarskck' => [
            'model' => \App\Models\SuratPengantarSkck::class,
            'view' => 'surat.pdf_skck',
            'aliases' => [
                'suratpengantarskck',
                'surat_pengantar_skck',
                'skck',
                'pdf_skck',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14780,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02487,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.50,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'skck',
        ],

        // Surat Keterangan Usaha
        'suratketeranganusaha' => [
            'model' => \App\Models\SuratKeteranganUsaha::class,
            'view' => 'surat.pdf_surat_keterangan_usaha',
            'aliases' => [
                'suratketeranganusaha',
                'surat_keterangan_usaha',
                'usaha',
                'pdf_surat_keterangan_usaha',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'No :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.14602,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02487,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.50,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_usaha',
        ],

        // Surat Keterangan Domisili Lembaga
        'suratketerangandomisililembaga' => [
            'model' => \App\Models\SuratKeteranganDomisiliLembaga::class,
            'view' => 'surat.pdf_surat_keterangan_domisili_lembaga',
            'aliases' => [
                'surat_keterangan_domisili_lembaga',
                'domisili_lembaga',
                'suratketerangandomisililembaga',
                'pdf_surat_keterangan_domisili_lembaga',
            ],
            'number_fields' => [
                'nomor_surat',
                'no_surat',
                'nomor',
            ],
            'number_label' => 'Nomor :',
            'include_number_label' => true,
            'allow_client_number_fallback' => true,
            'number_position_mode' => 'fixed',
            'number_page_index' => 0,
            'number_style' => [
                'pageIndex' => 0,
                'xRatio' => 0.05000,
                'yRatio' => 0.15508,
                'widthRatio' => 0.90000,
                'heightRatio' => 0.02647,
                'fontFamily' => 'Times New Roman',
                'fontSizePt' => 11.80,
                'alignment' => 'center',
                'bold' => false,
                'horizontalCorrectionPt' => 0.0,
                'verticalCorrectionPt' => -0.6,
            ],
            'filename_fields' => [
                'nama',
                'nama_lengkap',
                'nama_pelapor',
                'nama_pemohon',
                'nama_deklaran',
                'instansi_pemohon',
                'perihal',
            ],
            'filename_prefix' => 'surat_keterangan_domisili_lembaga',
        ],

    ],
];
